### ISSUE TITLE
While downloading the pertained weights: urllib.error.HTTPError: HTTP Error 403: The specified account is disabled.

### ISSUE THREAD

**Issue by Kaushal28** [lukemelas/EfficientNet-PyTorch#151]
I'm using EfficientNet-B1 pre trained weights and getting 403 HTTP status code. Here is the entire error log:

```
Downloading: "https://publicmodels.blob.core.windows.net/container/aa/efficientnet-b1-f1951068.pth" to /root/.cache/torch/checkpoints/efficientnet-b1-f1951068.pth
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    main()
  File "train.py", line 145, in main
    model = MODEL_DISPATCHER[BASE_MODEL](pretrained=True)
  File "/content/models.py", line 34, in __init__
    self.effNet = EfficientNet.from_pretrained('efficientnet-b1', in_channels=3)
  File "/usr/local/lib/python3.6/dist-packages/efficientnet_pytorch/model.py", line 211, in from_pretrained
    load_pretrained_weights(model, model_name, load_fc=(num_classes == 1000), advprop=advprop)
  File "/usr/local/lib/python3.6/dist-packages/efficientnet_pytorch/utils.py", line 327, in load_pretrained_weights
    state_dict = model_zoo.load_url(url_map_[model_name])
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 492, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 391, in download_url_to_file
    u = urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: The specified account is disabled.```

**Comment by vojtooo** [comment]
I wanted to use pretrained EfficientNet-B5 and I am encountering the same problem.

>  urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: The specified account is disabled.

I tried also to find how to use vanilla EfficientNet with a custom number of classes but was unable to find any.

**Comment by b02202050** [comment]
https://github.com/lukemelas/EfficientNet-PyTorch/issues/150#issuecomment-592909402

**Comment by Kaushal28** [comment]
@b02202050 Thanks for pointing out the Kaggle Dataset. Here is how you do it dynamically in your code:

```python
def custom_load_pretrained_weights(model, model_name, load_fc=True, advprop=False):
    """ Loads pretrained weights, and downloads if loading for the first time. """
    # AutoAugment or Advprop (different preprocessing)
    url_map_ = url_map_advprop if advprop else url_map
    state_dict = torch.load('/content/efficientnet-b1-dbc7070a.pth', map_location='cpu')
    if load_fc:
        model.load_state_dict(state_dict)
    else:
        state_dict.pop('_fc.weight')
        state_dict.pop('_fc.bias')
        res = model.load_state_dict(state_dict, strict=False)
        assert set(res.missing_keys) == set(['_fc.weight', '_fc.bias']), 'issue loading pretrained weights'
    print('Loaded pretrained weights for {}'.format(model_name))

from efficientnet_pytorch import utils
utils.load_pretrained_weights.__code__ = custom_load_pretrained_weights.__code__
```

After patching the function, use the library as it is. Just for information tagging: @vojtooo

**Comment by lukemelas** [comment]
See #150 -- fix is coming today!

**Comment by lukemelas** [comment]
Fixed! I'm closing this issue -- reopen if you encounter problems :)
