### ISSUE TITLE
How to fix '_pickle.UnpicklingError: invalid load key, '<' ' error in Pytorch

### ISSUE THREAD

**Issue by abbyyu** [lukemelas/EfficientNet-PyTorch#160]
# python 3.7, linux
Your code is really helpful, but when I ran the code ,there is a problem that

 '_pickle.UnpicklingError: invalid load key, '<' '.
Traceback (most recent call last):
  File "EfficientNet.py", line 67, in <module>
    model = EfficientNet.from_pretrained('efficientnet-b0',advprop=True).cuda()  
  File "/home/wangzeyu/EfficientNet-PyTorch/efficientnet_pytorch/model.py", line 211, in from_pretrained
    load_pretrained_weights(model, model_name, load_fc=(num_classes == 1000), advprop=advprop)
  File "/home/wangzeyu/EfficientNet-PyTorch/efficientnet_pytorch/utils.py", line 327, in load_pretrained_weights
    state_dict = model_zoo.load_url(url_map_[model_name])
  File "/home/wangzeyu/anaconda3/lib/python3.7/site-packages/torch/hub.py", line 499, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/wangzeyu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/wangzeyu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 603, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by beibuwandeluori** [comment]
I meet the same problem,I solved it by reload the pretrained model weight!, because my previous pretrained model weight is incomplete！you need to delete the previous weights in ~/.cache/torch/checkpoints
