### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by xjmxyt** [lukemelas/EfficientNet-PyTorch#171]
The model works right using cpu.
However, when I run the example in example.py using gpu, I get this error.

Traceback (most recent call last):
  File "train.py", line 53, in <module>
    summary(model, input_size=(1, 224, 224, 224))
  File "/home/LAB/qiaoyx/anaconda3/envs/xjm1/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/LAB/qiaoyx/anaconda3/envs/xjm1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/qiaoyx/anaconda3/envs/xjm1/lib/python3.7/site-packages/efficientnet_pytorch_3d/model.py", line 191, in forward
    x = self.extract_features(inputs)
  File "/home/LAB/qiaoyx/anaconda3/envs/xjm1/lib/python3.7/site-packages/efficientnet_pytorch_3d/model.py", line 173, in extract_features
    x = self._swish(self._bn0(self._conv_stem(inputs)))
  File "/home/LAB/qiaoyx/anaconda3/envs/xjm1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/LAB/qiaoyx/anaconda3/envs/xjm1/lib/python3.7/site-packages/efficientnet_pytorch_3d/utils.py", line 147, in forward
    x = F.conv3d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by P-DX** [comment]
hi, do you solve this problem?
could you share the solution with me please?

**Comment by xiaohuaibaoguigui** [comment]
add   
"model.to('cuda')"
before 
"summary(model, input_size=(1, 224, 224, 224))"
