### ISSUE TITLE
Kernel size mismatch to padded input

### ISSUE THREAD

**Issue by YB221** [lukemelas/EfficientNet-PyTorch#173]
Traceback (most recent call last):
  File "main.py", line 152, in <module>
    train_logger, train_batch_logger)
  File "/home/yashbhambhu_18je0949/PyTorch3DCNNs_UCF101/train.py", line 30, in train_epoch
    outputs = model(inputs)
  File "/home/yashbhambhu_18je0949/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yashbhambhu_18je0949/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/yashbhambhu_18je0949/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yashbhambhu_18je0949/PyTorch3DCNNs_UCF101/models/efficientnet.py", line 186, in forward
    x = self.extract_features(inputs)
  File "/home/yashbhambhu_18je0949/PyTorch3DCNNs_UCF101/models/efficientnet.py", line 175, in extract_features
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/home/yashbhambhu_18je0949/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yashbhambhu_18je0949/PyTorch3DCNNs_UCF101/models/efficientnet.py", line 75, in forward
    x = self._swish(self._bn1(self._depthwise_conv(x)))
  File "/home/yashbhambhu_18je0949/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yashbhambhu_18je0949/PyTorch3DCNNs_UCF101/models/efficient_utils.py", line 142, in forward
    x = F.conv3d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: Calculated padded input size per channel: (2 x 8 x 8). Kernel size: (3 x 3 x 3). Kernel size can't be greater than actual input size

**Comment by lukemelas** [comment]
I think this issue is better suited for the `PyTorch3DCNNs_UCF101` repo. I'm going to close this, but respond if you think it's an issue with this repo.
