### ISSUE TITLE
Can not load from pretrained?

### ISSUE THREAD

**Issue by playma** [lukemelas/EfficientNet-PyTorch#225]
Can not load from pretrained?

```
Traceback (most recent call last):
  File "/data/magiclens/apps/decensored_server/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/magiclens/apps/decensored_server/.venv/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/magiclens/apps/decensored_server/apps/video/tasks.py", line 200, in video_inference
    mosaic_classifier = EfficientNet.from_pretrained('efficientnet-b1', num_classes=2)
  File "/data/magiclens/apps/decensored_server/.venv/lib/python3.6/site-packages/efficientnet_pytorch/model.py", line 211, in from_pretrained
    self._conv_head = Conv2d(in_channels, out_channels, kernel_size=1, bias=False)
  File "/data/magiclens/apps/decensored_server/.venv/lib/python3.6/site-packages/efficientnet_pytorch/utils.py", line 327, in load_pretrained_weights
    ih, iw = (image_size, image_size) if isinstance(image_size, int) else image_size
  File "/data/magiclens/apps/decensored_server/.venv/lib/python3.6/site-packages/torch/hub.py", line 433, in load_state_dict_from_url
    If the object is already present in `model_dir`, it's deserialized and
  File "/data/magiclens/apps/decensored_server/.venv/lib/python3.6/site-packages/torch/hub.py", line 349, in _download_url_to_file
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by lukemelas** [comment]
What version of `efficientnet_pytorch` are you using?

**Comment by playma** [comment]
@lukemelas 0.7.0

**Comment by lukemelas** [comment]
Hmm, it works for me in a vanilla Colab notebook: 

https://ibb.co/kH96z4M
