### ISSUE TITLE
ImageNet example issue on Torch with CPU support

### ISSUE THREAD

**Issue by ticlazau** [lukemelas/EfficientNet-PyTorch#275]
Hello,

I am trying to run on CPU only, no CUDA available and I am facing the following issue:
- python main.py data -e -a 'efficientnet-b0' --pretrained

```
Loaded pretrained weights for efficientnet-b0
=> using pre-trained model 'efficientnet-b0'
Traceback (most recent call last):
  File "main.py", line 443, in <module>
    main()
  File "main.py", line 117, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 180, in main_worker
    model = torch.nn.DataParallel(model).cuda()
  File "/Users/coredump/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/Users/coredump/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/Users/coredump/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/Users/coredump/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/Users/coredump/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 491, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/Users/coredump/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 164, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```
Is anything I am missing?

Rgds,
FM

**Comment by lukemelas** [comment]
You should find the places in `main.py` with `.cuda()` and remove `.cuda()` (it should be around 5 places, the first of which is line 180, which caused your issue). 

I'm going to close this issue, but re-open it (or just comment) if you have any more questions!
