### ISSUE TITLE
ImageNet example problems

### ISSUE THREAD

**Issue by franciscorba** [lukemelas/EfficientNet-PyTorch#96]
I tried to run ImageNet example (using Tiny ImageNet) to understand how the code works and be able to train in my own datasets as asked in #4. 

Running resnet18 is fine:
`python main.py data --gpu 0`

But with others architectures it doesn't work. With EfficientNet and ResNet50 I got Out of Memory errors like in #18 and #49:

EfficientNet-B0
```python main.py data -a 'efficientnet-b0' --gpu 0
main.py:97: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Use GPU: 0 for training
=> creating model 'efficientnet-b0'
Using image size 224
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 443, in <module>
    main()
  File "main.py", line 115, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 265, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 307, in train
    output = model(images)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/model.py", line 193, in forward
    x = self.extract_features(inputs)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/model.py", line 182, in extract_features
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/model.py", line 78, in forward
    x = self._swish(self._bn1(self._depthwise_conv(x)))
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/utils.py", line 52, in forward
    return SwishImplementation.apply(x)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/utils.py", line 39, in forward
    result = i * torch.sigmoid(i)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu:58
```

EfficientNet-B3
```python main.py data -a 'efficientnet-b3' --gpu 0
main.py:97: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Use GPU: 0 for training
=> creating model 'efficientnet-b3'
Using image size 300
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 443, in <module>
    main()
  File "main.py", line 115, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 265, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 307, in train
    output = model(images)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/model.py", line 193, in forward
    x = self.extract_features(inputs)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/model.py", line 182, in extract_features
    x = block(x, drop_connect_rate=drop_connect_rate)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/model.py", line 77, in forward
    x = self._swish(self._bn0(self._expand_conv(inputs)))
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/utils.py", line 52, in forward
    return SwishImplementation.apply(x)
  File "/home/frbarbos/Workspace/EfficientNet-PyTorch/examples/imagenet/efficientnet_pytorch/utils.py", line 39, in forward
    result = i * torch.sigmoid(i)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu:58
```

ResNet50
```python main.py data -a 'resnet50' --gpu 0
main.py:97: UserWarning: You have chosen a specific GPU. This will completely disable data parallelism.
  warnings.warn('You have chosen a specific GPU. This will completely '
Use GPU: 0 for training
=> creating model 'resnet50'
Using image size 224
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 443, in <module>
    main()
  File "main.py", line 115, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main.py", line 265, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args)
  File "main.py", line 307, in train
    output = model(images)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torchvision/models/resnet.py", line 145, in forward
    x = self.layer2(x)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torchvision/models/resnet.py", line 81, in forward
    out = self.bn2(out)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 49, in forward
    self.training or not self.track_running_stats, self.momentum, self.eps)
  File "/home/frbarbos/anaconda2/envs/frbarbos10/lib/python3.6/site-packages/torch/nn/functional.py", line 1194, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu:58
```

I have tried in a GeForce GTX TITAN X and a Tesla K40c.

**Comment by franciscorba** [comment]
Ok, I think I solve this by reducing the batch size with the --batch-size option.
